/* tslint:disable */
/* eslint-disable */
/**
 * LCT Hack Parser
 * Cian.ru parser for LCT Hack
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RepairType } from './repair-type';
import { Segment } from './segment';
import { Walls } from './walls';
/**
 * 
 * @export
 * @interface ApartmentBase
 */
export interface ApartmentBase {
    /**
     * 
     * @type {string}
     * @memberof ApartmentBase
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof ApartmentBase
     */
    link?: string;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    lon: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    rooms: number;
    /**
     * 
     * @type {Segment}
     * @memberof ApartmentBase
     */
    segment: Segment;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    floors: number;
    /**
     * 
     * @type {Walls}
     * @memberof ApartmentBase
     */
    walls?: Walls;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    floor: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    apartmentArea: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    kitchenArea?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApartmentBase
     */
    hasBalcony?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    distanceToMetro?: number;
    /**
     * 
     * @type {RepairType}
     * @memberof ApartmentBase
     */
    quality?: RepairType;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    m2price?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentBase
     */
    price?: number;
}
