/* tslint:disable */
/* eslint-disable */
/**
 * LCT Hack Parser
 * Cian.ru parser for LCT Hack
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export enum Segment {
     = 'новостройка',
     = 'современное жилье',
     = 'старый жилой фонд'
}

