/* tslint:disable */
/* eslint-disable */
/**
 * LCT Hack Parser
 * Cian.ru parser for LCT Hack
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApartmentBase } from '../models';
import { HTTPValidationError } from '../models';
import { SearchBase } from '../models';
/**
 * ParserApi - axios parameter creator
 * @export
 */
export const ParserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Запустить парсинг данных и сообщить об этом пользователю
         * @summary Запуск парсинга данных
         * @param {SearchBase} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        parseParsePost: async (body: SearchBase, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling parseParsePost.');
            }
            const localVarPath = `/parse`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ParserApi - functional programming interface
 * @export
 */
export const ParserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Запустить парсинг данных и сообщить об этом пользователю
         * @summary Запуск парсинга данных
         * @param {SearchBase} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async parseParsePost(body: SearchBase, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<ApartmentBase>>>> {
            const localVarAxiosArgs = await ParserApiAxiosParamCreator(configuration).parseParsePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ParserApi - factory interface
 * @export
 */
export const ParserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Запустить парсинг данных и сообщить об этом пользователю
         * @summary Запуск парсинга данных
         * @param {SearchBase} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async parseParsePost(body: SearchBase, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<ApartmentBase>>> {
            return ParserApiFp(configuration).parseParsePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ParserApi - object-oriented interface
 * @export
 * @class ParserApi
 * @extends {BaseAPI}
 */
export class ParserApi extends BaseAPI {
    /**
     * Запустить парсинг данных и сообщить об этом пользователю
     * @summary Запуск парсинга данных
     * @param {SearchBase} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParserApi
     */
    public async parseParsePost(body: SearchBase, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<ApartmentBase>>> {
        return ParserApiFp(this.configuration).parseParsePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
